name: flutter_chat
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=2.18.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  flutter_screenutil: ^5.6.0
  firebase_storage: ^11.5.6
  cloud_firestore: ^4.2.0
  flutter_hooks: ^0.18.5+1
  octo_image: ^2.0.0
  cached_network_image: ^3.3.0
  badges: ^2.0.3
  provider: ^6.0.5
  path_provider: ^2.0.11
  image_picker: ^0.8.6
  flutter_easyloading: ^3.0.5
  event_bus: ^2.0.0
  flutter_chat_bubble: ^2.0.0
  fluttertoast: ^8.1.2
  date_format: ^2.0.7
  shared_preferences: ^2.0.15
  extended_image: ^8.2.0
  adaptive_dialog: ^2.0.0
  settings_ui: ^2.0.2
  wechat_assets_picker: ^8.8.0
  photo_manager: ^3.0.0-dev.1
  dio: ^4.0.6
  path: ^1.8.3
  flutter_native_splash: ^2.2.16
  record: ^5.0.4
  just_audio: ^0.9.36
  animated_text_kit: ^4.2.2
  flex_color_picker: ^3.0.0
  font_awesome_flutter: ^10.3.0
  google_sign_in: ^6.2.1
  flutter_svg: ^1.1.6
  flutter_spinkit: ^5.1.0
  firebase_remote_config: ^4.3.8
  url_launcher: ^6.1.7
  flutter_markdown: ^0.6.13
  flutter_highlighter: ^0.1.1
  google_fonts: ^6.1.0
  image_cropper: ^5.0.1
  awesome_notifications: ^0.7.4+1
  package_info_plus: ^5.0.1
  # agora_rtc_engine: ^6.1.0
  permission_handler: ^10.2.0
  uuid: ^3.0.6
  google_sign_in_web: ^0.12.3+1
  web_socket_channel: ^2.4.0
  universal_html: ^2.2.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/google_icon.svg
    - assets/github_icon.svg
    - assets/chat_gpt.svg
    - assets/new_message_sound.wav
flutter_native_splash:
  color: "#e1f5fe"
  image: assets/logo_lockup_flutter_vertical.png
  color_dark: "#042a49"
  image_dark: assets/logo_lockup_flutter_vertical_wht.png
  android: true
  ios: true
  web: false
  android_gravity: center
  fullerene: true
