name: flutter_chat
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.0
  flutter_screenutil: ^5.6.0
  firebase_storage: ^11.0.7
  cloud_firestore: ^4.2.0
  flutter_hooks: ^0.18.5+1
  octo_image: ^1.0.2
  cached_network_image: ^3.2.3
  badges: ^2.0.3
  provider: ^6.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
